import type { Metadata } from "next";
import { auth } from "@/lib/auth/auth";
import { db } from "@/lib/db/prisma";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { Topbar } from "@/components/topbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await auth();
  let currency = "USD";
  if (session?.user?.organizationId) {
    const organization = await db.orm.Organization
      .where({ id: session.user.organizationId })
      .first() as { currency?: string } | undefined;
    currency = organization?.currency ?? "USD";
  }

  return (
    <html
      lang="en"
      className="h-full antialiased"
      data-currency={currency}
    >
      <body className="flex min-h-full bg-zinc-50 dark:bg-zinc-900">
        <Sidebar />
        <div className="flex min-w-0 flex-1 flex-col">
          <Topbar />
          <main className="flex-1 overflow-y-auto p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
